version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=100519Mi
      - MYSQL_DATABASE=bdrestaurante
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
